const GameData = {
    // TerrainData
    '0': {
        '1': {name: '地面_正常', type: 'Ground', param1: '', param2: '', imgID: 'p1'},
        '2': {name: '地面_冰封', type: 'Ground', param1: '1', param2: '', imgID: 'p2'},
        '3': {name: '地面_岩浆', type: 'Ground', param1: '2', param2: '', imgID: 'p3'},
        '4': {name: '地面_岩石', type: 'Ground', param1: '3', param2: '', imgID: 'p4'},
        '5': {name: '水面', type: 'Water', param1: '', param2: '', imgID: 'g61'},
        '6': {name: '岩浆', type: 'Lava', param1: '', param2: '', imgID: 'g62'},
        '7': {name: '太空', type: 'Space', param1: '', param2: '', imgID: 'g63'},
        '11': {name: '墙体_正常', type: 'Wall', param1: '1', param2: 'g68', imgID: 'p11'},
        '12': {name: '墙体_水泥', type: 'Wall', param1: '2', param2: 'g69', imgID: 'p12'},
        '13': {name: '墙体_钢板', type: 'Wall', param1: '3', param2: 'g70', imgID: 'p13'},
        '14': {name: '墙体_晶壁', type: 'Wall', param1: '4', param2: 'g71', imgID: 'p14'}
    },
    //ItemData
    '1': {
        '11': {name: '墙体_正常', type: 'Wall', param1: '1', param2: 'g68', canUse: '', desc: '', desc2: '', imgID: 'p11'},
        '12': {name: '墙体_水泥', type: 'Wall', param1: '2', param2: 'g69', canUse: '', desc: '', desc2: '', imgID: 'p12'},
        '13': {name: '墙体_钢板', type: 'Wall', param1: '3', param2: 'g70', canUse: '', desc: '', desc2: '', imgID: 'p13'},
        '14': {name: '墙体_晶壁', type: 'Wall', param1: '4', param2: 'g71', canUse: '', desc: '', desc2: '', imgID: 'p14'},
        '15': {name: '黄门', type: 'Door', param1: '1', param2: 'g76', canUse: '', desc: '', desc2: '', imgID: 'p15'},
        '16': {name: '蓝门', type: 'Door', param1: '2', param2: 'g77', canUse: '', desc: '', desc2: '', imgID: 'p16'},
        '17': {name: '红门', type: 'Door', param1: '3', param2: 'g78', canUse: '', desc: '', desc2: '', imgID: 'p17'},
        '18': {name: '黑门', type: 'Door', param1: '4', param2: 'g79', canUse: '', desc: '', desc2: '', imgID: 'p18'},
        '19': {name: '蓝门', type: 'Door', param1: '5', param2: 'g80', canUse: '', desc: '', desc2: '', imgID: 'p19'},
        '20': {name: '绿门', type: 'Door', param1: '6', param2: 'g81', canUse: '', desc: '', desc2: '', imgID: 'p20'},
        '21': {name: '墙体_正常', type: 'FakeItem', param1: '11', param2: 'g72', canUse: '', desc: '', desc2: '', imgID: 'null'},
        '22': {name: '墙体_水泥', type: 'FakeItem', param1: '12', param2: 'g73', canUse: '', desc: '', desc2: '', imgID: 'null'},
        '23': {name: '墙体_钢板', type: 'FakeItem', param1: '13', param2: 'g74', canUse: '', desc: '', desc2: '', imgID: 'null'},
        '24': {name: '墙体_晶壁', type: 'FakeItem', param1: '14', param2: 'g75', canUse: '', desc: '', desc2: '', imgID: 'null'},
        '25': {name: '黄门', type: 'FakeItem', param1: '15', param2: 'g82', canUse: '', desc: '', desc2: '', imgID: 'null'},
        '26': {name: '蓝门', type: 'FakeItem', param1: '16', param2: 'g83', canUse: '', desc: '', desc2: '', imgID: 'null'},
        '27': {name: '红门', type: 'FakeItem', param1: '17', param2: 'g84', canUse: '', desc: '', desc2: '', imgID: 'null'},
        '28': {name: '黑门', type: 'FakeItem', param1: '18', param2: 'g85', canUse: '', desc: '', desc2: '', imgID: 'null'},
        '29': {name: '蓝门', type: 'FakeItem', param1: '19', param2: 'g86', canUse: '', desc: '', desc2: '', imgID: 'null'},
        '30': {name: '绿门', type: 'FakeItem', param1: '20', param2: 'g87', canUse: '', desc: '', desc2: '', imgID: 'null'},
        '31': {name: '下层', type: 'Lift', param1: '-1', param2: '', canUse: '', desc: '', desc2: '', imgID: 'p31'},
        '32': {name: '上层', type: 'Lift', param1: '1', param2: '', canUse: '', desc: '', desc2: '', imgID: 'p32'},
        '33': {name: '拳头', type: 'Weapon', param1: '1', param2: '0', canUse: '', desc: '', desc2: '', imgID: 'p33'},
        '34': {name: '爆炸', type: 'Null', param1: '', param2: '', canUse: '', desc: '', desc2: '', imgID: 'p34'},
        '35': {name: '星光1', type: 'Star', param1: '1', param2: '', canUse: '', desc: '', desc2: '', imgID: 'p35'},
        '36': {name: '星光2', type: 'Star', param1: '2', param2: '', canUse: '', desc: '', desc2: '', imgID: 'p36'},
        '37': {name: '星光3', type: 'Star', param1: '3', param2: '', canUse: '', desc: '', desc2: '', imgID: 'p37'},
        '38': {name: '商店左', type: 'Null', param1: '', param2: '', canUse: '', desc: '', desc2: '', imgID: 'p38'},
        '39': {name: '商店中', type: 'Null', param1: '', param2: '', canUse: '', desc: '', desc2: '', imgID: 'p39'},
        '40': {name: '商店右', type: 'Null', param1: '', param2: '', canUse: '', desc: '', desc2: '', imgID: 'p40'},
        '41': {name: '箭头_上', type: 'WalkLimit', param1: '1', param2: '', canUse: '', desc: '', desc2: '', imgID: 'p41'},
        '42': {name: '箭头_下', type: 'WalkLimit', param1: '3', param2: '', canUse: '', desc: '', desc2: '', imgID: 'p42'},
        '43': {name: '箭头_左', type: 'WalkLimit', param1: '2', param2: '', canUse: '', desc: '', desc2: '', imgID: 'p43'},
        '44': {name: '箭头_右', type: 'WalkLimit', param1: '4', param2: '', canUse: '', desc: '', desc2: '', imgID: 'p44'},
        '45': {name: '传送1', type: 'Teleport', param1: '1', param2: '', canUse: '', desc: '', desc2: '', imgID: 'g64'},
        '46': {name: '传送2', type: 'Teleport', param1: '2', param2: '', canUse: '', desc: '', desc2: '', imgID: 'g65'},
        '47': {name: '传送3', type: 'Teleport', param1: '3', param2: '', canUse: '', desc: '', desc2: '', imgID: 'g66'},
        '48': {name: '黑洞', type: 'Hole', param1: '', param2: '', canUse: '', desc: '', desc2: '', imgID: 'g67'},
        '51': {name: '短剑', type: 'Weapon', param1: '1', param2: '10', canUse: '1', desc: '虽然短，但是你还快啊', desc2: '确定切换到短剑吗？', imgID: 'p51'},
        '52': {name: '长剑', type: 'Weapon', param1: '1', param2: '15', canUse: '1', desc: '一寸长一寸强', desc2: '确定切换到长剑吗？', imgID: 'p52'},
        '53': {name: '骑士剑', type: 'Weapon', param1: '1', param2: '20', canUse: '1', desc: '圣骑士马克专用，7天包换', desc2: '确定切换到骑士剑吗？', imgID: 'p53'},
        '54': {name: '将军剑', type: 'Weapon', param1: '2', param2: '30', canUse: '1', desc: '陷阵之志，有死无生！', desc2: '确定切换到将军剑吗？', imgID: 'p54'},
        '55': {name: '罗兰誓约', type: 'Weapon', param1: '2', param2: '50', canUse: '1', desc: '罗兰贵族的专用佩剑', desc2: '确定切换到罗兰誓约吗？', imgID: 'p55'},
        '56': {name: '永夜之刃', type: 'Weapon', param1: '2', param2: '120', canUse: '1', desc: '天下武功，唯快不破', desc2: '确定切换到永夜之刃吗？', imgID: 'p56'},
        '57': {name: 'Saber', type: 'Weapon', param1: '3', param2: '180', canUse: '1', desc: 'MasterYoda\'s Concentration', desc2: '确定切换到Saber吗？', imgID: 'p57'},
        '58': {name: 'Scythe', type: 'Weapon', param1: '4', param2: '300', canUse: '1', desc: 'Come From The Deep', desc2: '确定切换到Scythe吗？', imgID: 'p58'},
        '59': {name: '警棍', type: 'Weapon', param1: '4', param2: '300', canUse: '1', desc: '双节警棍，两倍威力！', desc2: '确定切换到警棍吗？', imgID: 'p59'},
        '61': {name: '树枝', type: 'Wand', param1: '1', param2: '10', canUse: '1', desc: '光秃秃的树枝，能释放简单的魔法', desc2: '确定切换到冬青树枝吗？', imgID: 'p61'},
        '62': {name: '橡树枝', type: 'Wand', param1: '1', param2: '20', canUse: '1', desc: '由橡树枝做成的魔杖', desc2: '确定切换到橡树树枝吗？', imgID: 'p62'},
        '63': {name: '杏树魔杖', type: 'Wand', param1: '1', param2: '30', canUse: '1', desc: '弯曲的树枝可以用来敲人', desc2: '确定切换到杏树魔杖吗？', imgID: 'p63'},
        '64': {name: '梨花魔杖', type: 'Wand', param1: '1', param2: '40', canUse: '1', desc: '由珍贵的智慧梨花木做成', desc2: '确定切换到梨花魔杖吗？', imgID: 'p64'},
        '65': {name: '魔导法杖', type: 'Wand', param1: '1', param2: '60', canUse: '1', desc: '奖励给魔法学院十佳毕业生的魔杖', desc2: '确定切换到法师魔杖吗？', imgID: 'p65'},
        '66': {name: '月亮之上', type: 'Wand', param1: '2', param2: '200', canUse: '1', desc: '拜月教的神器', desc2: '确定切换到月亮之上吗？', imgID: 'p66'},
        '67': {name: 'Scallion', type: 'Wand', param1: '3', param2: '300', canUse: '1', desc: 'Miku\'s GreenFood', desc2: '确定切换到Scallion吗？', imgID: 'p67'},
        '68': {name: 'Death', type: 'Wand', param1: '4', param2: '500', canUse: '1', desc: 'Come From the Deep', desc2: '确定切换到Death吗？', imgID: 'p68'},
        '69': {name: '魔法扫把', type: 'Wand', param1: '2', param2: '200', canUse: '1', desc: '附带涡轮加速的魔法扫把', desc2: '确定切换到魔法扫把吗？', imgID: 'p69'},
        '71': {name: '红药', type: 'Med', param1: '50', param2: '0', canUse: '', desc: '', desc2: '', imgID: 'p71'},
        '72': {name: '蓝药', type: 'Med', param1: '0', param2: '200', canUse: '', desc: '', desc2: '', imgID: 'p72'},
        '73': {name: '大红药', type: 'Med', param1: '200', param2: '0', canUse: '', desc: '', desc2: '', imgID: 'p73'},
        '74': {name: '大蓝药', type: 'Med', param1: '0', param2: '500', canUse: '', desc: '', desc2: '', imgID: 'p74'},
        '75': {name: '爱心', type: 'SpecialMed', param1: '1', param2: '', canUse: '1', desc: '让你多一条命', desc2: '确定使用吗？', imgID: 'p75'},
        '76': {name: '药丸', type: 'SpecialMed', param1: '2', param2: '', canUse: '1', desc: '有效祛除负面效果', desc2: '确定使用吗？', imgID: 'p76'},
        '77': {name: '牛奶', type: 'SpecialMed', param1: '3', param2: '', canUse: '1', desc: '一瓶已经过期的牛奶', desc2: '确定使用吗？', imgID: 'p77'},
        '78': {name: '万能药剂', type: 'SpecialMed', param1: '4', param2: '', canUse: '1', desc: '大幅提高生命和魔法', desc2: '确定使用吗？', imgID: 'p78'},
        '79': {name: '绿色液体', type: 'SpecialMed', param1: '5', param2: '', canUse: '1', desc: '这个似乎有毒？', desc2: '确定使用吗？', imgID: 'p79'},
        '81': {name: '红钻', type: 'RedCrystal', param1: '1', param2: '0', canUse: '', desc: '物理攻击+1', desc2: '', imgID: 'p81'},
        '82': {name: '大红钻', type: 'RedCrystal', param1: '5', param2: '0', canUse: '', desc: '物理攻击+5', desc2: '', imgID: 'p82'},
        '83': {name: '红盾', type: 'RedCrystal', param1: '0', param2: '2', canUse: '', desc: '物理防御+2', desc2: '', imgID: 'p83'},
        '84': {name: '大红盾', type: 'RedCrystal', param1: '0', param2: '10', canUse: '', desc: '物理防御+10', desc2: '', imgID: 'p84'},
        '85': {name: '红宝石', type: 'RedCrystal', param1: '10', param2: '20', canUse: '', desc: '物理攻击+10物理防御+20', desc2: '', imgID: 'p85'},
        '91': {name: '蓝钻', type: 'BlueCrystal', param1: '1', param2: '0', canUse: '', desc: '魔法攻击+1', desc2: '', imgID: 'p91'},
        '92': {name: '大蓝钻', type: 'BlueCrystal', param1: '5', param2: '0', canUse: '', desc: '魔法攻击+5', desc2: '', imgID: 'p92'},
        '93': {name: '蓝盾', type: 'BlueCrystal', param1: '0', param2: '1', canUse: '', desc: '魔法防御+1', desc2: '', imgID: 'p93'},
        '94': {name: '大蓝盾', type: 'BlueCrystal', param1: '0', param2: '5', canUse: '', desc: '魔法防御+5', desc2: '', imgID: 'p94'},
        '95': {name: '蓝宝石', type: 'BlueCrystal', param1: '10', param2: '10', canUse: '', desc: '魔法攻击+10魔法防御+10', desc2: '', imgID: 'p95'},
        '101': {name: '黄钥匙', type: 'Key', param1: '1', param2: '', canUse: '', desc: '可以打开黄色的门', desc2: '', imgID: 'p101'},
        '102': {name: '蓝钥匙', type: 'Key', param1: '2', param2: '', canUse: '', desc: '可以打开蓝色的门', desc2: '', imgID: 'p102'},
        '103': {name: '红钥匙', type: 'Key', param1: '3', param2: '', canUse: '', desc: '可以打开红色的门', desc2: '', imgID: 'p103'},
        '104': {name: '绿钥匙', type: 'GreenKey', param1: '', param2: '', canUse: '', desc: '可以打开红色的门', desc2: '', imgID: 'p104'},
        '105': {name: '万能钥匙', type: 'SuperKey', param1: '', param2: '', canUse: '1', desc: '打开一层楼里面所有黄色、蓝色和红色门', desc2: '确定使用万能钥匙吗？', imgID: 'p105'},
        '106': {name: '拳头', type: 'Hand', param1: '', param2: '', canUse: '', desc: '', desc2: '', imgID: 'p106'},
        '107': {name: '拖鞋', type: 'Shoe', param1: '2', param2: '', canUse: '1', desc: '穿上之后，恢复正常速度', desc2: '确定穿上拖鞋吗？', imgID: 'p107'},
        '108': {name: '木箱', type: 'Box', param1: '', param2: '', canUse: '', desc: '', desc2: '', imgID: 'p108'},
        '109': {name: '礼物', type: 'Gift', param1: '', param2: '', canUse: '1', desc: '正版玩家的礼物', desc2: '确定打开吗？', imgID: 'p109'},
        '111': {name: '铲子', type: 'Spade', param1: '', param2: '', canUse: '1', desc: '在地面上挖洞，需要正对着地面', desc2: '确定使用铲子挖地吗？', imgID: 'p111'},
        '112': {name: '镐子', type: 'Pickaxe', param1: '', param2: '', canUse: '1', desc: '在墙壁上挖洞，需要正对着墙壁', desc2: '确定使用镐子挖墙吗？', imgID: 'p112'},
        '113': {name: '炸药', type: 'Bomb', param1: '', param2: '', canUse: '1', desc: '炸掉附近的怪物，首领除外', desc2: '确定使用炸药吗？', imgID: 'p113'},
        '114': {name: '爆破卷轴', type: 'SuperBomb', param1: '', param2: '', canUse: '1', desc: '炸掉一层楼的所有墙', desc2: '确定使用炸药吗？', imgID: 'p114'},
        '115': {name: '飞羽', type: 'TeleWand', param1: '', param2: '', canUse: '', desc: '可使用PgUp和PgDn跳到曾经去过的楼层', desc2: '', imgID: 'p115'},
        '116': {name: '传送杖', type: 'SwapWand', param1: '', param2: '', canUse: '1', desc: '咻一下就能跳到对面去', desc2: '确定传送到对面吗？', imgID: 'p116'},
        '117': {name: '蛙跳', type: 'FrogJump', param1: '', param2: '', canUse: '', desc: '可以翻过一堵墙', desc2: '', imgID: 'p117'},
        '118': {name: '天鹅羽毛', type: 'GooseFeather', param1: '', param2: '', canUse: '', desc: '学会游泳，并且不会被寒冷的地面冻伤', desc2: '', imgID: 'p118'},
        '119': {name: '凤凰羽毛', type: 'PhoenixFeather', param1: '', param2: '', canUse: '', desc: '学会在岩浆里游泳，并且不会被灼热的地面烫伤', desc2: '', imgID: 'p119'},
        '121': {name: '金币', type: 'Coin', param1: '1', param2: '', canUse: '', desc: '这是你的金币，省着点用', desc2: '', imgID: 'p121'},
        '122': {name: '一袋金币', type: 'Coin', param1: '100', param2: '', canUse: '', desc: '获得100金币', desc2: '', imgID: 'p122'},
        '123': {name: '水晶', type: 'Coin', param1: '500', param2: '', canUse: '', desc: '获得500金币', desc2: '', imgID: 'p123'},
        '124': {name: '大水晶', type: 'Coin', param1: '1000', param2: '', canUse: '', desc: '获得1000金币', desc2: '', imgID: 'p124'},
        '125': {name: '金卡', type: 'GoldenCard', param1: '', param2: '', canUse: '', desc: '可享受八折优惠', desc2: '', imgID: 'p125'},
        '126': {name: '拼图1', type: 'Puzzle', param1: '', param2: '', canUse: '1', desc: '不知道用处的拼图', desc2: '研究一下拼图？', imgID: 'p126'},
        '127': {name: '拼图2', type: 'Puzzle', param1: '', param2: '', canUse: '1', desc: '不知道用处的拼图', desc2: '研究一下拼图？', imgID: 'p127'},
        '128': {name: '拼图3', type: 'Puzzle', param1: '', param2: '', canUse: '1', desc: '不知道用处的拼图', desc2: '研究一下拼图？', imgID: 'p128'},
        '129': {name: '拼图4', type: 'Puzzle', param1: '', param2: '', canUse: '1', desc: '不知道用处的拼图', desc2: '研究一下拼图？', imgID: 'p129'},
        '130': {name: '兔子拼图', type: 'Rabbit', param1: '', param2: '', canUse: '', desc: '象征幸运的兔子，打怪金币翻倍', desc2: '', imgID: 'p130'},
        '131': {name: '宝典', type: 'MonsterBook', param1: '', param2: '', canUse: '', desc: '可以看到怪物伤害', desc2: '', imgID: 'p131'},
        '132': {name: '章节1', type: 'Paper', param1: '1', param2: '', canUse: '1', desc: '', desc2: '研究一下这张纸？', imgID: 'p132'},
        '133': {name: '章节2', type: 'Paper', param1: '2', param2: '', canUse: '1', desc: '', desc2: '研究一下这张纸？', imgID: 'p133'},
        '134': {name: '章节3', type: 'Paper', param1: '3', param2: '', canUse: '1', desc: '', desc2: '研究一下这张纸？', imgID: 'p134'},
        '135': {name: '无字天书', type: 'Book', param1: '', param2: '', canUse: '1', desc: '', desc2: '研究一下这本书？', imgID: 'p135'},
        '136': {name: '拳套', type: 'PhyAtkPlus', param1: '', param2: '', canUse: '', desc: '使物理攻击提高20%', desc2: '', imgID: 'p136'},
        '137': {name: '木盾', type: 'PhyDefPlus', param1: '', param2: '', canUse: '', desc: '使物理防御提高20%', desc2: '', imgID: 'p137'},
        '138': {name: '戒指', type: 'MagAtkPlus', param1: '', param2: '', canUse: '', desc: '使魔法攻击提高50%', desc2: '', imgID: 'p138'},
        '139': {name: '斗篷', type: 'MagDefPlus', param1: '', param2: '', canUse: '', desc: '使魔法防御提高50%', desc2: '', imgID: 'p139'},
        '140': {name: '跑鞋', type: 'Shoe', param1: '1', param2: '1', canUse: '1', desc: '穿上之后，可以跑得超快', desc2: '确定穿上跑鞋吗？', imgID: 'p140'},
        '141': {name: '盆栽', type: 'Pot', param1: '', param2: '', canUse: '', desc: '？？', desc2: '', imgID: 'p141'},
        '142': {name: '叶子', type: 'Leaf', param1: '', param2: '', canUse: '', desc: '？？', desc2: '', imgID: 'p142'},
        '143': {name: '呱太', type: 'Frog', param1: '', param2: '', canUse: '', desc: '？？', desc2: '', imgID: 'p143'},
        '144': {name: '苹果', type: 'Apple', param1: '', param2: '', canUse: '', desc: '？？', desc2: '', imgID: 'p144'},
        '145': {name: '布偶', type: 'Doll', param1: '', param2: '', canUse: '', desc: '？？', desc2: '', imgID: 'p145'},
        '146': {name: '大师球', type: 'MasterBall', param1: '', param2: '', canUse: '', desc: '可以捕捉皮卡丘', desc2: '', imgID: 'p146'},
        '147': {name: '未知蛋', type: 'Egg', param1: '', param2: '', canUse: '', desc: '移动步数达到1000才能孵化', desc2: '', imgID: 'p147'},
        '148': {name: '未知蛋', type: 'Egg', param1: '', param2: '', canUse: '', desc: '移动步数达到1000才能孵化', desc2: '', imgID: 'p148'},
        '149': {name: '皮卡丘', type: 'Pikachu', param1: '', param2: '', canUse: '', desc: '快看！野生的皮卡丘', desc2: '', imgID: 'p149'},
        '150': {name: '皮卡丘', type: 'Pikachu', param1: '', param2: '', canUse: '', desc: '上吧！皮卡丘！', desc2: '', imgID: 'p150'}
    },
    //MonsterData
    '2': {
        '1': {name: '精灵', type: 'NPC', exp: '10', coin: '1', hp: '100', mp: '0', atk: '10', def: '0', atk2: '0', def2: '0', imgID: 'g1'},
        '2': {name: '老人', type: 'NPC', exp: '10', coin: '1', hp: '100', mp: '0', atk: '10', def: '0', atk2: '0', def2: '0', imgID: 'g2'},
        '3': {name: '财主', type: 'NPC', exp: '10', coin: '1', hp: '100', mp: '0', atk: '10', def: '0', atk2: '0', def2: '0', imgID: 'g3'},
        '4': {name: '盗贼', type: 'NPC', exp: '10', coin: '1', hp: '100', mp: '0', atk: '10', def: '0', atk2: '0', def2: '0', imgID: 'g4'},
        '5': {name: '公主', type: 'NPC', exp: '10', coin: '1', hp: '100', mp: '0', atk: '10', def: '0', atk2: '0', def2: '0', imgID: 'g5'},
        '6': {name: '杀手', type: 'NPC', exp: '10', coin: '1', hp: '100', mp: '0', atk: '10', def: '0', atk2: '0', def2: '0', imgID: 'g6'},
        '9': {name: 'Carina', type: 'NPC', exp: '10', coin: '1', hp: '100', mp: '0', atk: '10', def: '0', atk2: '0', def2: '0', imgID: 'g9'},
        '10': {name: '商店', type: 'Shop', exp: '10', coin: '1', hp: '100', mp: '0', atk: '10', def: '0', atk2: '0', def2: '0', imgID: 'g10'},
        '11': {name: '??', type: '普通', exp: '10', coin: '1', hp: '100', mp: '0', atk: '10', def: '0', atk2: '0', def2: '0', imgID: 'g11'},
        '12': {name: '绿史莱姆', type: '普通', exp: '10', coin: '1', hp: '35', mp: '0', atk: '18', def: '1', atk2: '0', def2: '0', imgID: 'g12'},
        '13': {name: '红史莱姆', type: '普通', exp: '10', coin: '2', hp: '45', mp: '0', atk: '20', def: '2', atk2: '0', def2: '0', imgID: 'g13'},
        '14': {name: '小蝙蝠', type: '普通', exp: '10', coin: '3', hp: '35', mp: '0', atk: '38', def: '3', atk2: '0', def2: '0', imgID: 'g14'},
        '15': {name: '蓝衣法师', type: '普通', exp: '10', coin: '5', hp: '60', mp: '0', atk: '32', def: '8', atk2: '0', def2: '0', imgID: 'g15'},
        '16': {name: '骷髅杂兵', type: '普通', exp: '10', coin: '6', hp: '50', mp: '0', atk: '42', def: '6', atk2: '0', def2: '0', imgID: 'g16'},
        '17': {name: '骷髅战士', type: '普通', exp: '10', coin: '8', hp: '55', mp: '0', atk: '52', def: '12', atk2: '0', def2: '0', imgID: 'g17'},
        '18': {name: '骷髅队长', type: '精英', exp: '10', coin: '30', hp: '100', mp: '0', atk: '65', def: '15', atk2: '0', def2: '0', imgID: 'g18'},
        '21': {name: '黑史莱姆', type: '普通', exp: '10', coin: '8', hp: '130', mp: '0', atk: '60', def: '3', atk2: '0', def2: '0', imgID: 'g21'},
        '22': {name: '大蝙蝠', type: '普通', exp: '10', coin: '12', hp: '60', mp: '0', atk: '100', def: '8', atk2: '0', def2: '0', imgID: 'g22'},
        '23': {name: '兽人杂兵', type: '普通', exp: '10', coin: '18', hp: '260', mp: '0', atk: '85', def: '5', atk2: '0', def2: '0', imgID: 'g23'},
        '24': {name: '兽人战士', type: '普通', exp: '10', coin: '30', hp: '320', mp: '0', atk: '120', def: '15', atk2: '0', def2: '0', imgID: 'g24'},
        '25': {name: '石头怪', type: '普通', exp: '10', coin: '28', hp: '20', mp: '0', atk: '100', def: '68', atk2: '0', def2: '0', imgID: 'g25'},
        '26': {name: '低阶卫兵', type: '普通', exp: '10', coin: '12', hp: '50', mp: '0', atk: '48', def: '22', atk2: '0', def2: '0', imgID: 'g26'},
        '27': {name: '红衣法师', type: '普通', exp: '10', coin: '22', hp: '100', mp: '0', atk: '95', def: '30', atk2: '0', def2: '0', imgID: 'g27'},
        '28': {name: '审判法师', type: '精英', exp: '10', coin: '50', hp: '500', mp: '0', atk: '150', def: '35', atk2: '0', def2: '0', imgID: 'g28'},
        '31': {name: '史莱姆王子', type: '普通', exp: '10', coin: '40', hp: '400', mp: '0', atk: '150', def: '80', atk2: '0', def2: '0', imgID: 'g31'},
        '32': {name: '吸血蝙蝠', type: '普通', exp: '10', coin: '50', hp: '400', mp: '0', atk: '150', def: '80', atk2: '0', def2: '0', imgID: 'g32'},
        '33': {name: '骷髅卫兵', type: '普通', exp: '10', coin: '29', hp: '400', mp: '0', atk: '150', def: '80', atk2: '0', def2: '0', imgID: 'g33'},
        '34': {name: '骷髅法师', type: '普通', exp: '10', coin: '28', hp: '400', mp: '0', atk: '150', def: '80', atk2: '0', def2: '0', imgID: 'g34'},
        '35': {name: '左护法', type: '普通', exp: '10', coin: '80', hp: '400', mp: '0', atk: '150', def: '80', atk2: '0', def2: '0', imgID: 'g35'},
        '36': {name: '右护法', type: '普通', exp: '10', coin: '21', hp: '400', mp: '0', atk: '150', def: '80', atk2: '0', def2: '0', imgID: 'g36'},
        '37': {name: '左长老', type: '普通', exp: '10', coin: '90', hp: '400', mp: '0', atk: '150', def: '80', atk2: '0', def2: '0', imgID: 'g37'},
        '38': {name: '右长老', type: '普通', exp: '10', coin: '23', hp: '400', mp: '0', atk: '150', def: '80', atk2: '0', def2: '0', imgID: 'g38'},
        '39': {name: '石头怪', type: '精英', exp: '10', coin: '33', hp: '400', mp: '0', atk: '150', def: '80', atk2: '0', def2: '0', imgID: 'g39'},
        '41': {name: '中阶卫兵', type: '普通', exp: '10', coin: '100', hp: '1000', mp: '0', atk: '300', def: '120', atk2: '0', def2: '0', imgID: 'g41'},
        '42': {name: '忍者战士', type: '普通', exp: '10', coin: '100', hp: '1000', mp: '0', atk: '300', def: '120', atk2: '0', def2: '0', imgID: 'g42'},
        '43': {name: '鬼面战士', type: '普通', exp: '10', coin: '100', hp: '1000', mp: '0', atk: '300', def: '120', atk2: '0', def2: '0', imgID: 'g43'},
        '44': {name: '护甲战士', type: '普通', exp: '10', coin: '100', hp: '1000', mp: '0', atk: '300', def: '120', atk2: '0', def2: '0', imgID: 'g44'},
        '45': {name: '蓝衣教主', type: '普通', exp: '10', coin: '100', hp: '1000', mp: '0', atk: '300', def: '120', atk2: '0', def2: '0', imgID: 'g45'},
        '46': {name: '双手剑士', type: '普通', exp: '10', coin: '100', hp: '1000', mp: '0', atk: '300', def: '120', atk2: '0', def2: '0', imgID: 'g46'},
        '47': {name: '褐甲骑士', type: '普通', exp: '10', coin: '100', hp: '1000', mp: '0', atk: '300', def: '120', atk2: '0', def2: '0', imgID: 'g47'},
        '48': {name: '红甲骑士', type: '普通', exp: '10', coin: '100', hp: '1000', mp: '0', atk: '300', def: '120', atk2: '0', def2: '0', imgID: 'g48'},
        '49': {name: '红衣教主', type: '精英', exp: '10', coin: '100', hp: '1000', mp: '0', atk: '300', def: '120', atk2: '0', def2: '0', imgID: 'g49'},
        '51': {name: '高阶卫兵', type: '普通', exp: '10', coin: '100', hp: '5000', mp: '0', atk: '500', def: '200', atk2: '0', def2: '0', imgID: 'g51'},
        '52': {name: '幽暗战士', type: '普通', exp: '10', coin: '100', hp: '5000', mp: '0', atk: '500', def: '200', atk2: '0', def2: '0', imgID: 'g52'},
        '53': {name: '幽暗刺客', type: '普通', exp: '10', coin: '100', hp: '5000', mp: '0', atk: '500', def: '200', atk2: '0', def2: '0', imgID: 'g53'},
        '54': {name: '幽暗骑士', type: '普通', exp: '10', coin: '100', hp: '5000', mp: '0', atk: '500', def: '200', atk2: '0', def2: '0', imgID: 'g54'},
        '55': {name: '幽暗教主', type: '普通', exp: '10', coin: '100', hp: '5000', mp: '0', atk: '500', def: '200', atk2: '0', def2: '0', imgID: 'g55'},
        '56': {name: '幽暗公爵', type: '普通', exp: '10', coin: '100', hp: '5000', mp: '0', atk: '500', def: '200', atk2: '0', def2: '0', imgID: 'g56'},
        '57': {name: '幽暗圣裁', type: '精英', exp: '10', coin: '100', hp: '5000', mp: '0', atk: '500', def: '200', atk2: '0', def2: '0', imgID: 'g57'}
    }
};
const MapData = {
    '0': {
        pos: [6, 8],
        map: [
            ['         ', ' 11      ', ' 11      ', ' 11      ', '         ', '         ', '         ', '         ', '         '],
            ['         ', ' 11      ', ' 11      ', ' 11      ', '         ', '         ', '         ', '         ', '         '],
            ['         ', '         ', ' 11      ', ' 11      ', '         ', '         ', '         ', '         ', '         '],
            ['         ', '         ', '         ', '         ', '         ', ' 11      ', ' 11      ', '         ', ' 11      '],
            ['         ', '         ', '         ', '         ', '         ', '         ', '         ', '         ', '         '],
            ['         ', ' 11      ', ' 11      ', '         ', '         ', '         ', ' 11      ', ' 11      ', '    15   '],
            ['         ', '         ', ' 11      ', '         ', '         ', '         ', ' 11      ', '         ', '         '],
            ['         ', '         ', ' 11      ', '         ', '         ', '         ', ' 11      ', '         ', '         '],
            ['         ', '         ', ' 11      ', '         ', '         ', '         ', ' 11      ', '         ', '         ']]
    }
};
MapData.getPos = function (level) {
    return new Pos(level, 0, this[level].pos[0], this[level].pos[1]);
};
MapData.getVal = function (level, layer, row, col) {
    let mapVal = this[level].map[row][col];
    if (mapVal === undefined) console.log('地图数据错误！' + level + ',' + row + ',' + col);
    return parseInt(mapVal.substr(3 * layer, 3));
};
MapData.getValByPos = function (level, pos) {
    let mapVal = this[level].map[pos.row][pos.col];
    if (mapVal === undefined) console.log('地图数据错误！' + level + ',' + pos.row + ',' + pos.col);
    return parseInt(mapVal.substr(3 * pos.layer, 3));
};
MapData.isEmpty = function (level, row, col) {
    let mapVal = this[level].map[row][col];
    if (mapVal === undefined) console.log('地图数据错误！' + level + ',' + row + ',' + col);
    return parseInt(mapVal) === 0;
};
MapData.isEmptyByPos = function (pos) {
    let mapVal = this[pos.level].map[pos.row][pos.col];
    if (mapVal === undefined) console.log('地图数据错误！' + pos.toString());
    return mapVal === '         '; //因为parseInt对空格会异常
};
