const Config = {

    View_Width: 650,
    View_Height: 480,

    Map_MaxRow: 11,
    Map_MaxCol: 11,
    Map_MaxLayer: 3,
    Map_Cell: 32,

    State_Game: 0,
    State_Menu: 1,
    State_PK: 2,

    Render_MapX: 234,
    Render_MapY: 64
};

const TerrainData = {
    "1": {name: "Ground_Normal", type: "Ground", param1: "", param2: "", imgID: "p1"},
    "2": {name: "Ground_Cold", type: "Ground", param1: "1", param2: "", imgID: "p2"},
    "3": {name: "Ground_Hot", type: "Ground", param1: "2", param2: "", imgID: "p3"},
    "4": {name: "Ground_Stone", type: "Ground", param1: "3", param2: "", imgID: "p4"},
    "5": {name: "Water", type: "Water", param1: "", param2: "", imgID: "g61"},
    "6": {name: "Lava", type: "Lava", param1: "", param2: "", imgID: "g62"},
    "7": {name: "Space", type: "Space", param1: "", param2: "", imgID: "g63"},
    "11": {name: "Wall_Normal", type: "Wall", param1: "1", param2: "g68", imgID: "p11"},
    "12": {name: "Wall_Stone", type: "Wall", param1: "2", param2: "g69", imgID: "p11"},
    "13": {name: "Wall_Steel", type: "Wall", param1: "3", param2: "g70", imgID: "p11"},
    "14": {name: "Wall_Crystal", type: "Wall", param1: "4", param2: "g71", imgID: "p11"}
};
const ItemData = {
    "11": {name: "墙体_正常", type: "Wall", param1: "1", param2: "g68", canUse: "", desc: "", desc2: "", imgID: "p11"},
    "12": {name: "墙体_水泥", type: "Wall", param1: "2", param2: "g69", canUse: "", desc: "", desc2: "", imgID: "p12"},
    "13": {name: "墙体_钢板", type: "Wall", param1: "3", param2: "g70", canUse: "", desc: "", desc2: "", imgID: "p13"},
    "14": {name: "墙体_晶壁", type: "Wall", param1: "4", param2: "g71", canUse: "", desc: "", desc2: "", imgID: "p14"},
    "15": {name: "黄门", type: "Door", param1: "1", param2: "g76", canUse: "", desc: "", desc2: "", imgID: "p15"},
    "16": {name: "蓝门", type: "Door", param1: "2", param2: "g77", canUse: "", desc: "", desc2: "", imgID: "p16"},
    "17": {name: "红门", type: "Door", param1: "3", param2: "g78", canUse: "", desc: "", desc2: "", imgID: "p17"},
    "18": {name: "黑门", type: "Door", param1: "4", param2: "g79", canUse: "", desc: "", desc2: "", imgID: "p18"},
    "19": {name: "蓝门", type: "Door", param1: "5", param2: "g80", canUse: "", desc: "", desc2: "", imgID: "p19"},
    "20": {name: "绿门", type: "Door", param1: "6", param2: "g81", canUse: "", desc: "", desc2: "", imgID: "p20"},
    "21": {
        name: "墙体_正常",
        type: "FakeItem",
        param1: "11",
        param2: "g72",
        canUse: "",
        desc: "",
        desc2: "",
        imgID: "null"
    },
    "22": {
        name: "墙体_水泥",
        type: "FakeItem",
        param1: "12",
        param2: "g73",
        canUse: "",
        desc: "",
        desc2: "",
        imgID: "null"
    },
    "23": {
        name: "墙体_钢板",
        type: "FakeItem",
        param1: "13",
        param2: "g74",
        canUse: "",
        desc: "",
        desc2: "",
        imgID: "null"
    },
    "24": {
        name: "墙体_晶壁",
        type: "FakeItem",
        param1: "14",
        param2: "g75",
        canUse: "",
        desc: "",
        desc2: "",
        imgID: "null"
    },
    "25": {name: "黄门", type: "FakeItem", param1: "15", param2: "g82", canUse: "", desc: "", desc2: "", imgID: "null"},
    "26": {name: "蓝门", type: "FakeItem", param1: "16", param2: "g83", canUse: "", desc: "", desc2: "", imgID: "null"},
    "27": {name: "红门", type: "FakeItem", param1: "17", param2: "g84", canUse: "", desc: "", desc2: "", imgID: "null"},
    "28": {name: "黑门", type: "FakeItem", param1: "18", param2: "g85", canUse: "", desc: "", desc2: "", imgID: "null"},
    "29": {name: "蓝门", type: "FakeItem", param1: "19", param2: "g86", canUse: "", desc: "", desc2: "", imgID: "null"},
    "30": {name: "绿门", type: "FakeItem", param1: "20", param2: "g87", canUse: "", desc: "", desc2: "", imgID: "null"},
    "31": {name: "下层", type: "Lift", param1: "-1", param2: "", canUse: "", desc: "", desc2: "", imgID: "p31"},
    "32": {name: "上层", type: "Lift", param1: "1", param2: "", canUse: "", desc: "", desc2: "", imgID: "p32"},
    "33": {name: "拳头", type: "Weapon", param1: "1", param2: "0", canUse: "", desc: "", desc2: "", imgID: "p33"},
    "34": {name: "爆炸", type: "Null", param1: "", param2: "", canUse: "", desc: "", desc2: "", imgID: "p34"},
    "35": {name: "星光1", type: "Star", param1: "1", param2: "", canUse: "", desc: "", desc2: "", imgID: "p35"},
    "36": {name: "星光2", type: "Star", param1: "2", param2: "", canUse: "", desc: "", desc2: "", imgID: "p36"},
    "37": {name: "星光3", type: "Star", param1: "3", param2: "", canUse: "", desc: "", desc2: "", imgID: "p37"},
    "38": {name: "商店左", type: "Null", param1: "", param2: "", canUse: "", desc: "", desc2: "", imgID: "p38"},
    "39": {name: "商店中", type: "Null", param1: "", param2: "", canUse: "", desc: "", desc2: "", imgID: "p39"},
    "40": {name: "商店右", type: "Null", param1: "", param2: "", canUse: "", desc: "", desc2: "", imgID: "p40"},
    "41": {name: "箭头_上", type: "WalkLimit", param1: "1", param2: "", canUse: "", desc: "", desc2: "", imgID: "p41"},
    "42": {name: "箭头_下", type: "WalkLimit", param1: "3", param2: "", canUse: "", desc: "", desc2: "", imgID: "p42"},
    "43": {name: "箭头_左", type: "WalkLimit", param1: "2", param2: "", canUse: "", desc: "", desc2: "", imgID: "p43"},
    "44": {name: "箭头_右", type: "WalkLimit", param1: "4", param2: "", canUse: "", desc: "", desc2: "", imgID: "p44"},
    "45": {name: "传送1", type: "Teleport", param1: "1", param2: "", canUse: "", desc: "", desc2: "", imgID: "g64"},
    "46": {name: "传送2", type: "Teleport", param1: "2", param2: "", canUse: "", desc: "", desc2: "", imgID: "g65"},
    "47": {name: "传送3", type: "Teleport", param1: "3", param2: "", canUse: "", desc: "", desc2: "", imgID: "g66"},
    "48": {name: "黑洞", type: "Hole", param1: "", param2: "", canUse: "", desc: "", desc2: "", imgID: "g67"},
    "51": {
        name: "短剑",
        type: "Weapon",
        param1: "1",
        param2: "10",
        canUse: "1",
        desc: "虽然短，但是你还快啊",
        desc2: "确定切换到短剑吗？",
        imgID: "p51"
    },
    "52": {
        name: "长剑",
        type: "Weapon",
        param1: "1",
        param2: "15",
        canUse: "1",
        desc: "一寸长一寸强",
        desc2: "确定切换到长剑吗？",
        imgID: "p52"
    },
    "53": {
        name: "骑士剑",
        type: "Weapon",
        param1: "1",
        param2: "20",
        canUse: "1",
        desc: "圣骑士马克专用，7天包换",
        desc2: "确定切换到骑士剑吗？",
        imgID: "p53"
    },
    "54": {
        name: "将军剑",
        type: "Weapon",
        param1: "2",
        param2: "30",
        canUse: "1",
        desc: "陷阵之志，有死无生！",
        desc2: "确定切换到将军剑吗？",
        imgID: "p54"
    },
    "55": {
        name: "罗兰誓约",
        type: "Weapon",
        param1: "2",
        param2: "50",
        canUse: "1",
        desc: "罗兰贵族的专用佩剑",
        desc2: "确定切换到罗兰誓约吗？",
        imgID: "p55"
    },
    "56": {
        name: "永夜之刃",
        type: "Weapon",
        param1: "2",
        param2: "120",
        canUse: "1",
        desc: "天下武功，唯快不破",
        desc2: "确定切换到永夜之刃吗？",
        imgID: "p56"
    },
    "57": {
        name: "Saber",
        type: "Weapon",
        param1: "3",
        param2: "180",
        canUse: "1",
        desc: "MasterYoda's Concentration",
        desc2: "确定切换到Saber吗？",
        imgID: "p57"
    },
    "58": {
        name: "Scythe",
        type: "Weapon",
        param1: "4",
        param2: "300",
        canUse: "1",
        desc: "ComeFromTheDeep",
        desc2: "确定切换到Scythe吗？",
        imgID: "p58"
    },
    "59": {
        name: "警棍",
        type: "Weapon",
        param1: "4",
        param2: "300",
        canUse: "1",
        desc: "双节警棍，两倍威力！",
        desc2: "确定切换到警棍吗？",
        imgID: "p59"
    },
    "61": {
        name: "树枝",
        type: "Wand",
        param1: "1",
        param2: "10",
        canUse: "1",
        desc: "光秃秃的树枝，能释放简单的魔法",
        desc2: "确定切换到冬青树枝吗？",
        imgID: "p61"
    },
    "62": {
        name: "橡树枝",
        type: "Wand",
        param1: "1",
        param2: "20",
        canUse: "1",
        desc: "由橡树枝做成的魔杖",
        desc2: "确定切换到橡树树枝吗？",
        imgID: "p62"
    },
    "63": {
        name: "杏树魔杖",
        type: "Wand",
        param1: "1",
        param2: "30",
        canUse: "1",
        desc: "弯曲的树枝可以用来敲人",
        desc2: "确定切换到杏树魔杖吗？",
        imgID: "p63"
    },
    "64": {
        name: "梨花魔杖",
        type: "Wand",
        param1: "1",
        param2: "40",
        canUse: "1",
        desc: "由珍贵的智慧梨花木做成",
        desc2: "确定切换到梨花魔杖吗？",
        imgID: "p64"
    },
    "65": {
        name: "魔导法杖",
        type: "Wand",
        param1: "1",
        param2: "60",
        canUse: "1",
        desc: "奖励给魔法学院十佳毕业生的魔杖",
        desc2: "确定切换到法师魔杖吗？",
        imgID: "p65"
    },
    "66": {
        name: "月亮之上",
        type: "Wand",
        param1: "2",
        param2: "200",
        canUse: "1",
        desc: "拜月教的神器",
        desc2: "确定切换到月亮之上吗？",
        imgID: "p66"
    },
    "67": {
        name: "Scallion",
        type: "Wand",
        param1: "3",
        param2: "300",
        canUse: "1",
        desc: "Miku'sGreenFood",
        desc2: "确定切换到Scallion吗？",
        imgID: "p67"
    },
    "68": {
        name: "Death",
        type: "Wand",
        param1: "4",
        param2: "500",
        canUse: "1",
        desc: "ComeFromtheDeep",
        desc2: "确定切换到Death吗？",
        imgID: "p68"
    },
    "69": {
        name: "魔法扫把",
        type: "Wand",
        param1: "2",
        param2: "200",
        canUse: "1",
        desc: "附带涡轮加速的魔法扫把",
        desc2: "确定切换到魔法扫把吗？",
        imgID: "p69"
    },
    "71": {name: "红药", type: "Med", param1: "50", param2: "0", canUse: "", desc: "", desc2: "", imgID: "p71"},
    "72": {name: "蓝药", type: "Med", param1: "0", param2: "200", canUse: "", desc: "", desc2: "", imgID: "p72"},
    "73": {name: "大红药", type: "Med", param1: "200", param2: "0", canUse: "", desc: "", desc2: "", imgID: "p73"},
    "74": {name: "大蓝药", type: "Med", param1: "0", param2: "500", canUse: "", desc: "", desc2: "", imgID: "p74"},
    "75": {
        name: "爱心",
        type: "SpecialMed",
        param1: "1",
        param2: "",
        canUse: "1",
        desc: "让你多一条命",
        desc2: "确定使用吗？",
        imgID: "p75"
    },
    "76": {
        name: "药丸",
        type: "SpecialMed",
        param1: "2",
        param2: "",
        canUse: "1",
        desc: "有效祛除负面效果",
        desc2: "确定使用吗？",
        imgID: "p76"
    },
    "77": {
        name: "牛奶",
        type: "SpecialMed",
        param1: "3",
        param2: "",
        canUse: "1",
        desc: "一瓶已经过期的牛奶",
        desc2: "确定使用吗？",
        imgID: "p77"
    },
    "78": {
        name: "万能药剂",
        type: "SpecialMed",
        param1: "4",
        param2: "",
        canUse: "1",
        desc: "大幅提高生命和魔法",
        desc2: "确定使用吗？",
        imgID: "p78"
    },
    "79": {
        name: "绿色液体",
        type: "SpecialMed",
        param1: "5",
        param2: "",
        canUse: "1",
        desc: "这个似乎有毒？",
        desc2: "确定使用吗？",
        imgID: "p79"
    },
    "81": {
        name: "红钻",
        type: "RedCrystal",
        param1: "1",
        param2: "0",
        canUse: "",
        desc: "物理攻击+1",
        desc2: "",
        imgID: "p81"
    },
    "82": {
        name: "大红钻",
        type: "RedCrystal",
        param1: "5",
        param2: "0",
        canUse: "",
        desc: "物理攻击+5",
        desc2: "",
        imgID: "p82"
    },
    "83": {
        name: "红盾",
        type: "RedCrystal",
        param1: "0",
        param2: "2",
        canUse: "",
        desc: "物理防御+2",
        desc2: "",
        imgID: "p83"
    },
    "84": {
        name: "大红盾",
        type: "RedCrystal",
        param1: "0",
        param2: "10",
        canUse: "",
        desc: "物理防御+10",
        desc2: "",
        imgID: "p84"
    },
    "85": {
        name: "红宝石",
        type: "RedCrystal",
        param1: "10",
        param2: "20",
        canUse: "",
        desc: "物理攻击+10物理防御+20",
        desc2: "",
        imgID: "p85"
    },
    "91": {
        name: "蓝钻",
        type: "BlueCrystal",
        param1: "1",
        param2: "0",
        canUse: "",
        desc: "魔法攻击+1",
        desc2: "",
        imgID: "p91"
    },
    "92": {
        name: "大蓝钻",
        type: "BlueCrystal",
        param1: "5",
        param2: "0",
        canUse: "",
        desc: "魔法攻击+5",
        desc2: "",
        imgID: "p92"
    },
    "93": {
        name: "蓝盾",
        type: "BlueCrystal",
        param1: "0",
        param2: "1",
        canUse: "",
        desc: "魔法防御+1",
        desc2: "",
        imgID: "p93"
    },
    "94": {
        name: "大蓝盾",
        type: "BlueCrystal",
        param1: "0",
        param2: "5",
        canUse: "",
        desc: "魔法防御+5",
        desc2: "",
        imgID: "p94"
    },
    "95": {
        name: "蓝宝石",
        type: "BlueCrystal",
        param1: "10",
        param2: "10",
        canUse: "",
        desc: "魔法攻击+10魔法防御+10",
        desc2: "",
        imgID: "p95"
    },
    "101": {name: "黄钥匙", type: "Key", param1: "1", param2: "", canUse: "", desc: "可以打开黄色的门", desc2: "", imgID: "p101"},
    "102": {name: "蓝钥匙", type: "Key", param1: "2", param2: "", canUse: "", desc: "可以打开蓝色的门", desc2: "", imgID: "p102"},
    "103": {name: "红钥匙", type: "Key", param1: "3", param2: "", canUse: "", desc: "可以打开红色的门", desc2: "", imgID: "p103"},
    "104": {
        name: "绿钥匙",
        type: "GreenKey",
        param1: "",
        param2: "",
        canUse: "",
        desc: "可以打开红色的门",
        desc2: "",
        imgID: "p104"
    },
    "105": {
        name: "万能钥匙",
        type: "SuperKey",
        param1: "",
        param2: "",
        canUse: "1",
        desc: "打开一层楼里面所有黄色、蓝色和红色门",
        desc2: "确定使用万能钥匙吗？",
        imgID: "p105"
    },
    "106": {name: "拳头", type: "Hand", param1: "", param2: "", canUse: "", desc: "", desc2: "", imgID: "p106"},
    "107": {
        name: "拖鞋",
        type: "Shoe",
        param1: "2",
        param2: "",
        canUse: "1",
        desc: "穿上之后，恢复正常速度",
        desc2: "确定穿上拖鞋吗？",
        imgID: "p107"
    },
    "108": {name: "木箱", type: "Box", param1: "", param2: "", canUse: "", desc: "", desc2: "", imgID: "p108"},
    "109": {
        name: "礼物",
        type: "Gift",
        param1: "",
        param2: "",
        canUse: "1",
        desc: "正版玩家的礼物",
        desc2: "确定打开吗？",
        imgID: "p109"
    },
    "111": {
        name: "铲子",
        type: "Spade",
        param1: "",
        param2: "",
        canUse: "1",
        desc: "在地面上挖洞，需要正对着地面",
        desc2: "确定使用铲子挖地吗？",
        imgID: "p111"
    },
    "112": {
        name: "镐子",
        type: "Pickaxe",
        param1: "",
        param2: "",
        canUse: "1",
        desc: "在墙壁上挖洞，需要正对着墙壁",
        desc2: "确定使用镐子挖墙吗？",
        imgID: "p112"
    },
    "113": {
        name: "炸药",
        type: "Bomb",
        param1: "",
        param2: "",
        canUse: "1",
        desc: "炸掉附近的怪物，首领除外",
        desc2: "确定使用炸药吗？",
        imgID: "p113"
    },
    "114": {
        name: "爆破卷轴",
        type: "SuperBomb",
        param1: "",
        param2: "",
        canUse: "1",
        desc: "炸掉一层楼的所有墙",
        desc2: "确定使用炸药吗？",
        imgID: "p114"
    },
    "115": {
        name: "飞羽",
        type: "TeleWand",
        param1: "",
        param2: "",
        canUse: "",
        desc: "可使用PgUp和PgDn跳到曾经去过的楼层",
        desc2: "",
        imgID: "p115"
    },
    "116": {
        name: "传送杖",
        type: "SwapWand",
        param1: "",
        param2: "",
        canUse: "1",
        desc: "咻一下就能跳到对面去",
        desc2: "确定传送到对面吗？",
        imgID: "p116"
    },
    "117": {
        name: "蛙跳",
        type: "FrogJump",
        param1: "",
        param2: "",
        canUse: "",
        desc: "可以翻过一堵墙",
        desc2: "",
        imgID: "p117"
    },
    "118": {
        name: "天鹅羽毛",
        type: "GooseFeather",
        param1: "",
        param2: "",
        canUse: "",
        desc: "学会游泳，并且不会被寒冷的地面冻伤",
        desc2: "",
        imgID: "p118"
    },
    "119": {
        name: "凤凰羽毛",
        type: "PhoenixFeather",
        param1: "",
        param2: "",
        canUse: "",
        desc: "学会在岩浆里游泳，并且不会被灼热的地面烫伤",
        desc2: "",
        imgID: "p119"
    },
    "121": {
        name: "金币",
        type: "Coin",
        param1: "1",
        param2: "",
        canUse: "",
        desc: "这是你的金币，省着点用",
        desc2: "",
        imgID: "p121"
    },
    "122": {
        name: "一袋金币",
        type: "Coin",
        param1: "100",
        param2: "",
        canUse: "",
        desc: "获得100金币",
        desc2: "",
        imgID: "p122"
    },
    "123": {name: "水晶", type: "Coin", param1: "500", param2: "", canUse: "", desc: "获得500金币", desc2: "", imgID: "p123"},
    "124": {
        name: "大水晶",
        type: "Coin",
        param1: "1000",
        param2: "",
        canUse: "",
        desc: "获得1000金币",
        desc2: "",
        imgID: "p124"
    },
    "125": {
        name: "金卡",
        type: "GoldenCard",
        param1: "",
        param2: "",
        canUse: "",
        desc: "可享受八折优惠",
        desc2: "",
        imgID: "p125"
    },
    "126": {
        name: "拼图1",
        type: "Puzzle",
        param1: "",
        param2: "",
        canUse: "1",
        desc: "不知道用处的拼图",
        desc2: "研究一下拼图？",
        imgID: "p126"
    },
    "127": {
        name: "拼图2",
        type: "Puzzle",
        param1: "",
        param2: "",
        canUse: "1",
        desc: "不知道用处的拼图",
        desc2: "研究一下拼图？",
        imgID: "p127"
    },
    "128": {
        name: "拼图3",
        type: "Puzzle",
        param1: "",
        param2: "",
        canUse: "1",
        desc: "不知道用处的拼图",
        desc2: "研究一下拼图？",
        imgID: "p128"
    },
    "129": {
        name: "拼图4",
        type: "Puzzle",
        param1: "",
        param2: "",
        canUse: "1",
        desc: "不知道用处的拼图",
        desc2: "研究一下拼图？",
        imgID: "p129"
    },
    "130": {
        name: "兔子拼图",
        type: "Rabbit",
        param1: "",
        param2: "",
        canUse: "",
        desc: "象征幸运的兔子，打怪金币翻倍",
        desc2: "",
        imgID: "p130"
    },
    "131": {
        name: "宝典",
        type: "MonsterBook",
        param1: "",
        param2: "",
        canUse: "",
        desc: "可以看到怪物伤害",
        desc2: "",
        imgID: "p131"
    },
    "132": {
        name: "章节1",
        type: "Paper",
        param1: "1",
        param2: "",
        canUse: "1",
        desc: "",
        desc2: "研究一下这张纸？",
        imgID: "p132"
    },
    "133": {
        name: "章节2",
        type: "Paper",
        param1: "2",
        param2: "",
        canUse: "1",
        desc: "",
        desc2: "研究一下这张纸？",
        imgID: "p133"
    },
    "134": {
        name: "章节3",
        type: "Paper",
        param1: "3",
        param2: "",
        canUse: "1",
        desc: "",
        desc2: "研究一下这张纸？",
        imgID: "p134"
    },
    "135": {
        name: "无字天书",
        type: "Book",
        param1: "",
        param2: "",
        canUse: "1",
        desc: "",
        desc2: "研究一下这本书？",
        imgID: "p135"
    },
    "136": {
        name: "拳套",
        type: "PhyAtkPlus",
        param1: "",
        param2: "",
        canUse: "",
        desc: "使物理攻击提高20%",
        desc2: "",
        imgID: "p136"
    },
    "137": {
        name: "木盾",
        type: "PhyDefPlus",
        param1: "",
        param2: "",
        canUse: "",
        desc: "使物理防御提高20%",
        desc2: "",
        imgID: "p137"
    },
    "138": {
        name: "戒指",
        type: "MagAtkPlus",
        param1: "",
        param2: "",
        canUse: "",
        desc: "使魔法攻击提高50%",
        desc2: "",
        imgID: "p138"
    },
    "139": {
        name: "斗篷",
        type: "MagDefPlus",
        param1: "",
        param2: "",
        canUse: "",
        desc: "使魔法防御提高50%",
        desc2: "",
        imgID: "p139"
    },
    "140": {
        name: "跑鞋",
        type: "Shoe",
        param1: "1",
        param2: "1",
        canUse: "1",
        desc: "穿上之后，可以跑得超快",
        desc2: "确定穿上跑鞋吗？",
        imgID: "p140"
    },
    "141": {name: "盆栽", type: "Pot", param1: "", param2: "", canUse: "", desc: "？？", desc2: "", imgID: "p141"},
    "142": {name: "叶子", type: "Leaf", param1: "", param2: "", canUse: "", desc: "？？", desc2: "", imgID: "p142"},
    "143": {name: "呱太", type: "Frog", param1: "", param2: "", canUse: "", desc: "？？", desc2: "", imgID: "p143"},
    "144": {name: "苹果", type: "Apple", param1: "", param2: "", canUse: "", desc: "？？", desc2: "", imgID: "p144"},
    "145": {name: "布偶", type: "Doll", param1: "", param2: "", canUse: "", desc: "？？", desc2: "", imgID: "p145"},
    "146": {
        name: "大师球",
        type: "MasterBall",
        param1: "",
        param2: "",
        canUse: "",
        desc: "可以捕捉皮卡丘",
        desc2: "",
        imgID: "p146"
    },
    "147": {
        name: "未知蛋",
        type: "Egg",
        param1: "",
        param2: "",
        canUse: "",
        desc: "移动步数达到1000才能孵化",
        desc2: "",
        imgID: "p147"
    },
    "148": {
        name: "未知蛋",
        type: "Egg",
        param1: "",
        param2: "",
        canUse: "",
        desc: "移动步数达到1000才能孵化",
        desc2: "",
        imgID: "p148"
    },
    "149": {
        name: "皮卡丘",
        type: "Pikachu",
        param1: "",
        param2: "",
        canUse: "",
        desc: "快看！野生的皮卡丘",
        desc2: "",
        imgID: "p149"
    },
    "150": {name: "皮卡丘", type: "Pikachu", param1: "", param2: "", canUse: "", desc: "上吧！皮卡丘！", desc2: "", imgID: "p150"}
};
const ImgData = {
    "p1": {imgFile: "pic", x: 0, y: 0},
    "p2": {imgFile: "pic", x: 32, y: 0},
    "p3": {imgFile: "pic", x: 64, y: 0},
    "p4": {imgFile: "pic", x: 96, y: 0},
    "p11": {imgFile: "pic", x: 0, y: 32},
    "p12": {imgFile: "pic", x: 32, y: 32},
    "p13": {imgFile: "pic", x: 64, y: 32},
    "p14": {imgFile: "pic", x: 96, y: 32},
    "p15": {imgFile: "pic", x: 128, y: 32},
    "p16": {imgFile: "pic", x: 160, y: 32},
    "p17": {imgFile: "pic", x: 192, y: 32},
    "p18": {imgFile: "pic", x: 224, y: 32},
    "p19": {imgFile: "pic", x: 256, y: 32},
    "p20": {imgFile: "pic", x: 288, y: 32},
    "p31": {imgFile: "pic", x: 0, y: 96},
    "p32": {imgFile: "pic", x: 32, y: 96},
    "p33": {imgFile: "pic", x: 64, y: 96},
    "p34": {imgFile: "pic", x: 96, y: 96},
    "p35": {imgFile: "pic", x: 128, y: 96},
    "p36": {imgFile: "pic", x: 160, y: 96},
    "p37": {imgFile: "pic", x: 192, y: 96},
    "p38": {imgFile: "pic", x: 224, y: 96},
    "p39": {imgFile: "pic", x: 256, y: 96},
    "p40": {imgFile: "pic", x: 288, y: 96},
    "p41": {imgFile: "pic", x: 0, y: 128},
    "p42": {imgFile: "pic", x: 32, y: 128},
    "p43": {imgFile: "pic", x: 64, y: 128},
    "p44": {imgFile: "pic", x: 96, y: 128},
    "p51": {imgFile: "pic", x: 0, y: 160},
    "p52": {imgFile: "pic", x: 32, y: 160},
    "p53": {imgFile: "pic", x: 64, y: 160},
    "p54": {imgFile: "pic", x: 96, y: 160},
    "p55": {imgFile: "pic", x: 128, y: 160},
    "p56": {imgFile: "pic", x: 160, y: 160},
    "p57": {imgFile: "pic", x: 192, y: 160},
    "p58": {imgFile: "pic", x: 224, y: 160},
    "p59": {imgFile: "pic", x: 256, y: 160},
    "p61": {imgFile: "pic", x: 0, y: 192},
    "p62": {imgFile: "pic", x: 32, y: 192},
    "p63": {imgFile: "pic", x: 64, y: 192},
    "p64": {imgFile: "pic", x: 96, y: 192},
    "p65": {imgFile: "pic", x: 128, y: 192},
    "p66": {imgFile: "pic", x: 160, y: 192},
    "p67": {imgFile: "pic", x: 192, y: 192},
    "p68": {imgFile: "pic", x: 224, y: 192},
    "p69": {imgFile: "pic", x: 256, y: 192},
    "p71": {imgFile: "pic", x: 0, y: 224},
    "p72": {imgFile: "pic", x: 32, y: 224},
    "p73": {imgFile: "pic", x: 64, y: 224},
    "p74": {imgFile: "pic", x: 96, y: 224},
    "p75": {imgFile: "pic", x: 128, y: 224},
    "p76": {imgFile: "pic", x: 160, y: 224},
    "p77": {imgFile: "pic", x: 192, y: 224},
    "p78": {imgFile: "pic", x: 224, y: 224},
    "p79": {imgFile: "pic", x: 256, y: 224},
    "p81": {imgFile: "pic", x: 0, y: 256},
    "p82": {imgFile: "pic", x: 32, y: 256},
    "p83": {imgFile: "pic", x: 64, y: 256},
    "p84": {imgFile: "pic", x: 96, y: 256},
    "p85": {imgFile: "pic", x: 128, y: 256},
    "p91": {imgFile: "pic", x: 0, y: 288},
    "p92": {imgFile: "pic", x: 32, y: 288},
    "p93": {imgFile: "pic", x: 64, y: 288},
    "p94": {imgFile: "pic", x: 96, y: 288},
    "p95": {imgFile: "pic", x: 128, y: 288},
    "p101": {imgFile: "pic", x: 0, y: 320},
    "p102": {imgFile: "pic", x: 32, y: 320},
    "p103": {imgFile: "pic", x: 64, y: 320},
    "p104": {imgFile: "pic", x: 96, y: 320},
    "p105": {imgFile: "pic", x: 128, y: 320},
    "p106": {imgFile: "pic", x: 160, y: 320},
    "p107": {imgFile: "pic", x: 192, y: 320},
    "p108": {imgFile: "pic", x: 224, y: 320},
    "p109": {imgFile: "pic", x: 256, y: 320},
    "p111": {imgFile: "pic", x: 0, y: 352},
    "p112": {imgFile: "pic", x: 32, y: 352},
    "p113": {imgFile: "pic", x: 64, y: 352},
    "p114": {imgFile: "pic", x: 96, y: 352},
    "p115": {imgFile: "pic", x: 128, y: 352},
    "p116": {imgFile: "pic", x: 160, y: 352},
    "p117": {imgFile: "pic", x: 192, y: 352},
    "p118": {imgFile: "pic", x: 224, y: 352},
    "p119": {imgFile: "pic", x: 256, y: 352},
    "p121": {imgFile: "pic", x: 0, y: 384},
    "p122": {imgFile: "pic", x: 32, y: 384},
    "p123": {imgFile: "pic", x: 64, y: 384},
    "p124": {imgFile: "pic", x: 96, y: 384},
    "p125": {imgFile: "pic", x: 128, y: 384},
    "p126": {imgFile: "pic", x: 160, y: 384},
    "p127": {imgFile: "pic", x: 192, y: 384},
    "p128": {imgFile: "pic", x: 224, y: 384},
    "p129": {imgFile: "pic", x: 256, y: 384},
    "p130": {imgFile: "pic", x: 288, y: 384},
    "p131": {imgFile: "pic", x: 0, y: 416},
    "p132": {imgFile: "pic", x: 32, y: 416},
    "p133": {imgFile: "pic", x: 64, y: 416},
    "p134": {imgFile: "pic", x: 96, y: 416},
    "p135": {imgFile: "pic", x: 128, y: 416},
    "p136": {imgFile: "pic", x: 160, y: 416},
    "p137": {imgFile: "pic", x: 192, y: 416},
    "p138": {imgFile: "pic", x: 224, y: 416},
    "p139": {imgFile: "pic", x: 256, y: 416},
    "p140": {imgFile: "pic", x: 288, y: 416},
    "p141": {imgFile: "pic", x: 0, y: 448},
    "p142": {imgFile: "pic", x: 32, y: 448},
    "p143": {imgFile: "pic", x: 64, y: 448},
    "p144": {imgFile: "pic", x: 96, y: 448},
    "p145": {imgFile: "pic", x: 128, y: 448},
    "p146": {imgFile: "pic", x: 160, y: 448},
    "p147": {imgFile: "pic", x: 192, y: 448},
    "p148": {imgFile: "pic", x: 224, y: 448},
    "p149": {imgFile: "pic", x: 256, y: 448},
    "p150": {imgFile: "pic", x: 288, y: 448},
    "g1": {imgFile: "gif", x: 0, y: 0},
    "g2": {imgFile: "gif", x: 0, y: 32},
    "g3": {imgFile: "gif", x: 0, y: 64},
    "g4": {imgFile: "gif", x: 0, y: 96},
    "g5": {imgFile: "gif", x: 0, y: 128},
    "g6": {imgFile: "gif", x: 0, y: 160},
    "g9": {imgFile: "gif", x: 0, y: 256},
    "g10": {imgFile: "gif", x: 0, y: 288},
    "g11": {imgFile: "gif", x: 0, y: 320},
    "g12": {imgFile: "gif", x: 0, y: 352},
    "g13": {imgFile: "gif", x: 0, y: 384},
    "g14": {imgFile: "gif", x: 0, y: 416},
    "g15": {imgFile: "gif", x: 0, y: 448},
    "g16": {imgFile: "gif", x: 0, y: 480},
    "g17": {imgFile: "gif", x: 0, y: 512},
    "g18": {imgFile: "gif", x: 0, y: 544},
    "g21": {imgFile: "gif", x: 0, y: 640},
    "g22": {imgFile: "gif", x: 0, y: 672},
    "g23": {imgFile: "gif", x: 0, y: 704},
    "g24": {imgFile: "gif", x: 0, y: 736},
    "g25": {imgFile: "gif", x: 0, y: 768},
    "g26": {imgFile: "gif", x: 0, y: 800},
    "g27": {imgFile: "gif", x: 0, y: 832},
    "g28": {imgFile: "gif", x: 0, y: 864},
    "g31": {imgFile: "gif", x: 0, y: 960},
    "g32": {imgFile: "gif", x: 0, y: 992},
    "g33": {imgFile: "gif", x: 0, y: 1024},
    "g34": {imgFile: "gif", x: 0, y: 1056},
    "g35": {imgFile: "gif", x: 0, y: 1088},
    "g36": {imgFile: "gif", x: 0, y: 1120},
    "g37": {imgFile: "gif", x: 0, y: 1152},
    "g38": {imgFile: "gif", x: 0, y: 1184},
    "g39": {imgFile: "gif", x: 0, y: 1216},
    "g41": {imgFile: "gif", x: 0, y: 1280},
    "g42": {imgFile: "gif", x: 0, y: 1312},
    "g43": {imgFile: "gif", x: 0, y: 1344},
    "g44": {imgFile: "gif", x: 0, y: 1376},
    "g45": {imgFile: "gif", x: 0, y: 1408},
    "g46": {imgFile: "gif", x: 0, y: 1440},
    "g47": {imgFile: "gif", x: 0, y: 1472},
    "g48": {imgFile: "gif", x: 0, y: 1504},
    "g49": {imgFile: "gif", x: 0, y: 1536},
    "g51": {imgFile: "gif", x: 0, y: 1600},
    "g52": {imgFile: "gif", x: 0, y: 1632},
    "g53": {imgFile: "gif", x: 0, y: 1664},
    "g54": {imgFile: "gif", x: 0, y: 1696},
    "g55": {imgFile: "gif", x: 0, y: 1728},
    "g56": {imgFile: "gif", x: 0, y: 1760},
    "g57": {imgFile: "gif", x: 0, y: 1792},
    "g61": {imgFile: "gif", x: 0, y: 1920},
    "g62": {imgFile: "gif", x: 0, y: 1952},
    "g63": {imgFile: "gif", x: 0, y: 1984},
    "g64": {imgFile: "gif", x: 0, y: 2016},
    "g65": {imgFile: "gif", x: 0, y: 2048},
    "g66": {imgFile: "gif", x: 0, y: 2080},
    "g67": {imgFile: "gif", x: 0, y: 2112},
    "g68": {imgFile: "gif", x: 0, y: 2144},
    "g69": {imgFile: "gif", x: 0, y: 2176},
    "g70": {imgFile: "gif", x: 0, y: 2208},
    "g71": {imgFile: "gif", x: 0, y: 2240},
    "g76": {imgFile: "gif", x: 0, y: 2400},
    "g77": {imgFile: "gif", x: 0, y: 2432},
    "g78": {imgFile: "gif", x: 0, y: 2464},
    "g79": {imgFile: "gif", x: 0, y: 2496},
    "g80": {imgFile: "gif", x: 0, y: 2528},
    "g81": {imgFile: "gif", x: 0, y: 2560},
    "g72": {imgFile: "gif", x: 0, y: 2272},
    "g73": {imgFile: "gif", x: 0, y: 2304},
    "g74": {imgFile: "gif", x: 0, y: 2336},
    "g75": {imgFile: "gif", x: 0, y: 2368},
    "g82": {imgFile: "gif", x: 0, y: 2592},
    "g83": {imgFile: "gif", x: 0, y: 2624},
    "g84": {imgFile: "gif", x: 0, y: 2656},
    "g85": {imgFile: "gif", x: 0, y: 2688},
    "g86": {imgFile: "gif", x: 0, y: 2720},
    "g87": {imgFile: "gif", x: 0, y: 2752}
};
const MapData = {
    "0": {
        pos: {row: 6, col: 8},
        map: [0, 6, 0, 11, 0, 7, 0, 11, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 11, 0, 0, 0, 11, 11, 11, 11, 0, 0, 0, 11, 11, 11, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 11, 11, 11, 0, 0, 0, 11, 11, 11, 11, 0, 0, 0, 11, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 108, 0, 0, 61, 0, 65, 0, 0, 109, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    }
};

let Global = {
    FPS: 0,
    init: false,
    state: Config.State_Game,
    canMove: false
};
